version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'harel_thing_or_two'
      POSTGRES_PASSWORD: 'Thing_or_2'
      POSTGRES_DB: 'songs_db'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
